// This file is auto-generated by @hey-api/openapi-ts

export const ApiAssetPublicSchema = {
    properties: {
        method: {
            type: 'string',
            maxLength: 10,
            title: 'Method'
        },
        uri_pattern: {
            type: 'string',
            maxLength: 512,
            title: 'Uri Pattern'
        },
        params_schema: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Params Schema'
        },
        header_schema: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Header Schema'
        },
        last_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Seen At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['method', 'uri_pattern', 'id', 'created_at'],
    title: 'ApiAssetPublic'
} as const;

export const ApiAssetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApiAssetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApiAssetsPublic'
} as const;

export const ApiEndpointDetailResponseSchema = {
    properties: {
        endpoint: {
            '$ref': '#/components/schemas/ApiEndpointPublic'
        },
        module_name: {
            type: 'string',
            title: 'Module Name'
        },
        traffic_count: {
            type: 'integer',
            title: 'Traffic Count'
        },
        last_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Seen At'
        },
        recent_traffic: {
            items: {
                '$ref': '#/components/schemas/TrafficRecordPublic'
            },
            type: 'array',
            title: 'Recent Traffic'
        }
    },
    type: 'object',
    required: ['endpoint', 'module_name', 'traffic_count', 'last_seen_at', 'recent_traffic'],
    title: 'ApiEndpointDetailResponse'
} as const;

export const ApiEndpointPublicSchema = {
    properties: {
        method: {
            type: 'string',
            maxLength: 10,
            title: 'Method'
        },
        path: {
            type: 'string',
            maxLength: 512,
            title: 'Path'
        },
        level: {
            '$ref': '#/components/schemas/EndpointLevel',
            default: 'p3'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        service_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Name'
        },
        source_type: {
            '$ref': '#/components/schemas/SourceType',
            default: 'auto_discovered'
        },
        module_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Module Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['method', 'path', 'id', 'created_at'],
    title: 'ApiEndpointPublic'
} as const;

export const ApiEndpointsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApiEndpointPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApiEndpointsPublic'
} as const;

export const ApiKeyCreateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        rate_limit: {
            type: 'integer',
            title: 'Rate Limit',
            default: 100
        }
    },
    type: 'object',
    title: 'ApiKeyCreate'
} as const;

export const ApiKeyPublicSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        rate_limit: {
            type: 'integer',
            title: 'Rate Limit',
            default: 100
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        total_calls: {
            type: 'integer',
            title: 'Total Calls'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['id', 'key', 'total_calls', 'user_id'],
    title: 'ApiKeyPublic'
} as const;

export const ApiKeysPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApiKeyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApiKeysPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const EndpointLevelSchema = {
    type: 'string',
    enum: ['p0', 'p1', 'p2', 'p3'],
    title: 'EndpointLevel'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const SecurityTestReportPublicSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id'
        },
        vulnerability_found: {
            type: 'boolean',
            title: 'Vulnerability Found',
            default: false
        },
        details: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['task_id', 'asset_id', 'id', 'created_at'],
    title: 'SecurityTestReportPublic'
} as const;

export const SecurityTestReportsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SecurityTestReportPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SecurityTestReportsPublic'
} as const;

export const SecurityTestTaskSchema = {
    properties: {
        target_asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Asset Id'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        payload_type: {
            type: 'string',
            maxLength: 50,
            title: 'Payload Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: ['target_asset_id', 'payload_type'],
    title: 'SecurityTestTask'
} as const;

export const ServiceStatusSchema = {
    type: 'string',
    enum: ['active', 'deprecated'],
    title: 'ServiceStatus'
} as const;

export const SourceTypeSchema = {
    type: 'string',
    enum: ['auto_discovered', 'documented', 'mocked', 'zombie'],
    title: 'SourceType'
} as const;

export const StatisticsSchema = {
    properties: {
        collect_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collect Count',
            description: '收藏数',
            examples: [4109]
        },
        comment_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Count',
            description: '评论数',
            examples: [925]
        },
        digg_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Digg Count',
            description: '点赞数',
            examples: [31667]
        },
        download_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Download Count',
            description: '下载数（可能为 null 或缺失）',
            examples: [
                null
            ]
        },
        share_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Share Count',
            description: '分享数',
            examples: [5437]
        }
    },
    type: 'object',
    title: 'Statistics'
} as const;

export const SystemModuleSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        service_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Prefix'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus',
            default: 'active'
        },
        total_traffic_count: {
            type: 'integer',
            title: 'Total Traffic Count',
            default: 0
        },
        unique_traffic_count: {
            type: 'integer',
            title: 'Unique Traffic Count',
            default: 0
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        deprecated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deprecated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SystemModule'
} as const;

export const SystemModuleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        service_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Prefix'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus',
            default: 'active'
        },
        total_traffic_count: {
            type: 'integer',
            title: 'Total Traffic Count',
            default: 0
        },
        unique_traffic_count: {
            type: 'integer',
            title: 'Unique Traffic Count',
            default: 0
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        deprecated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deprecated At'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SystemModuleCreate'
} as const;

export const SystemModuleStatsSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        interfaces: {
            type: 'integer',
            title: 'Interfaces'
        },
        documented: {
            type: 'integer',
            title: 'Documented'
        },
        shadow: {
            type: 'integer',
            title: 'Shadow'
        },
        last_scanned_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Scanned At'
        },
        owner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        total_traffic_count: {
            type: 'integer',
            title: 'Total Traffic Count'
        },
        unique_traffic_count: {
            type: 'integer',
            title: 'Unique Traffic Count'
        },
        last_active_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Active At'
        },
        deprecated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deprecated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'description', 'interfaces', 'documented', 'shadow', 'last_scanned_at', 'owner', 'status', 'total_traffic_count', 'unique_traffic_count', 'last_active_at', 'deprecated_at'],
    title: 'SystemModuleStats'
} as const;

export const SystemModuleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        service_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Prefix'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'SystemModuleUpdate'
} as const;

export const SystemModulesStatsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SystemModuleStats'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SystemModulesStatsResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrafficRecordPublicSchema = {
    properties: {
        endpoint_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endpoint Id'
        },
        method: {
            type: 'string',
            maxLength: 10,
            title: 'Method'
        },
        real_uri: {
            type: 'string',
            maxLength: 1024,
            title: 'Real Uri'
        },
        headers: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headers'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        source_ip: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Ip'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['method', 'real_uri', 'id', 'created_at'],
    title: 'TrafficRecordPublic'
} as const;

export const TrafficRecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TrafficRecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TrafficRecordsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VideoDataSchema = {
    properties: {
        audio_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Url',
            description: '音频（BGM）直链',
            examples: ['https://...mp3']
        },
        aweme_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Aweme Id',
            description: '作品 ID',
            examples: ['7606984523657579819']
        },
        cover_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Url',
            description: '封面图直链',
            examples: ['https://...jpg']
        },
        create_time: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Create Time',
            description: '发布时间（格式化后的字符串）',
            examples: ['2026-02-15 09:55:00']
        },
        desc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Desc',
            description: '作品文案/描述',
            examples: ['...']
        },
        duration: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration',
            description: '时长（单位以第三方返回为准）',
            examples: [1074560]
        },
        statistics: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Statistics'
                },
                {
                    type: 'null'
                }
            ],
            description: '统计信息'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: '标题（通常与 desc 一致）',
            examples: ['...']
        },
        video_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Video Url',
            description: '视频播放直链',
            examples: ['https://...mp4']
        }
    },
    type: 'object',
    title: 'VideoData',
    examples: [
        {
            audio_url: 'https://sf5-hl-ali-cdn-tos.douyinstatic.com/obj/ies-music/7606956349372615475.mp3',
            aweme_id: '7606984523657579819',
            cover_url: 'https://p3-sign.douyinpic.com/obj/c8510002be9a3a61aad2?lk3s=138a59ce&x-expires=1774706400&x-signature=9uhjhXrSMU9Z4Gz%2BtmsmMr9VG%2B4%3D&from=327834062',
            create_time: '2026-02-15 09:55:00',
            desc: '勇闯非洲野生动物黑市，一路被敲诈勒索，这里什么都吃实在恐怖 #交换世界计划 #春节旅行好去处 #尼日利亚 #新年旅行第一站',
            duration: 1074560,
            statistics: {
                collect_count: 4109,
                comment_count: 925,
                digg_count: 31667,
                share_count: 5437
            },
            title: '勇闯非洲野生动物黑市，一路被敲诈勒索，这里什么都吃实在恐怖 #交换世界计划 #春节旅行好去处 #尼日利亚 #新年旅行第一站',
            video_url: 'https://v5-dy-o-abtest.zjcdn.com/02999f81e98ce2f438d4303bc418c395/69b57d03/video/tos/cn/tos-cn-ve-15/oo4CKGm5Ud2CIffDLcAuQIEGRAFMRYfEEQenhq/?a=1128&ch=26&cr=13&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=2381&bt=2381&cs=0&ds=6&ft=r0yIZ26Td95~~iSYsiI9B4yoFIKrHgSFS4fyRBHCnzyN9QZgxRyqkZ&mime_type=video_mp4&qs=0&rc=Zzs6ZjQ3OTczMzlnZWY8NUBpMzVveXQ5cnVxOTMzNGkzM0AuNV5hLmM1NTYxXzQyLTFiYSMvcjFrMmRzLTVhLS1kLTBzcw%3D%3D&btag=c0010e000b8009&cdn_type=1&cquery=103Y_100b_104i_103Q_103W&dy_q=1773497025&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20260314220345592C096DA77FAFB95A71&pdp=online_xy&pwid=1&req_cdn_type=r'
        }
    ]
} as const;

export const VideoResponseSchema = {
    properties: {
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message',
            description: '提示信息',
            examples: ['解析成功']
        },
        data: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoData'
                },
                {
                    type: 'null'
                }
            ],
            description: '解析出的作品数据'
        }
    },
    type: 'object',
    title: 'VideoResponse',
    examples: [
        {
            data: {
                audio_url: 'https://sf5-hl-ali-cdn-tos.douyinstatic.com/obj/ies-music/7606956349372615475.mp3',
                aweme_id: '7606984523657579819',
                cover_url: 'https://p3-sign.douyinpic.com/obj/c8510002be9a3a61aad2?lk3s=138a59ce&x-expires=1774706400&x-signature=9uhjhXrSMU9Z4Gz%2BtmsmMr9VG%2B4%3D&from=327834062',
                create_time: '2026-02-15 09:55:00',
                desc: '勇闯非洲野生动物黑市，一路被敲诈勒索，这里什么都吃实在恐怖 #交换世界计划 #春节旅行好去处 #尼日利亚 #新年旅行第一站',
                duration: 1074560,
                statistics: {
                    collect_count: 4109,
                    comment_count: 925,
                    digg_count: 31667,
                    share_count: 5437
                },
                title: '勇闯非洲野生动物黑市，一路被敲诈勒索，这里什么都吃实在恐怖 #交换世界计划 #春节旅行好去处 #尼日利亚 #新年旅行第一站',
                video_url: 'https://v5-dy-o-abtest.zjcdn.com/02999f81e98ce2f438d4303bc418c395/69b57d03/video/tos/cn/tos-cn-ve-15/oo4CKGm5Ud2CIffDLcAuQIEGRAFMRYfEEQenhq/?a=1128&ch=26&cr=13&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=2381&bt=2381&cs=0&ds=6&ft=r0yIZ26Td95~~iSYsiI9B4yoFIKrHgSFS4fyRBHCnzyN9QZgxRyqkZ&mime_type=video_mp4&qs=0&rc=Zzs6ZjQ3OTczMzlnZWY8NUBpMzVveXQ5cnVxOTMzNGkzM0AuNV5hLmM1NTYxXzQyLTFiYSMvcjFrMmRzLTVhLS1kLTBzcw%3D%3D&btag=c0010e000b8009&cdn_type=1&cquery=103Y_100b_104i_103Q_103W&dy_q=1773497025&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=20260314220345592C096DA77FAFB95A71&pdp=online_xy&pwid=1&req_cdn_type=r'
            },
            message: '解析成功'
        }
    ]
} as const;