// This file is auto-generated by @hey-api/openapi-ts

export type ApiAssetPublic = {
    method: string;
    uri_pattern: string;
    params_schema?: ({
    [key: string]: unknown;
} | null);
    header_schema?: ({
    [key: string]: unknown;
} | null);
    last_seen_at?: (string | null);
    id: string;
    created_at: (string | null);
};

export type ApiAssetsPublic = {
    data: Array<ApiAssetPublic>;
    count: number;
};

export type ApiEndpointDetailResponse = {
    endpoint: ApiEndpointPublic;
    module_id: string;
    module_name: string;
    service_name: string;
    traffic_count: number;
    last_seen_at: (string | null);
    recent_traffic: Array<TrafficRecordPublic>;
};

export type ApiEndpointPublic = {
    method: string;
    path: string;
    name?: (string | null);
    description?: (string | null);
    service_name?: (string | null);
    source_type?: SourceType;
    module_id?: (string | null);
    id: string;
    created_at: (string | null);
};

export type ApiEndpointsPublic = {
    data: Array<ApiEndpointPublic>;
    count: number;
};

export type ApiKeyCreate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: boolean;
    rate_limit?: number;
};

export type ApiKeyPublic = {
    name?: (string | null);
    description?: (string | null);
    is_active?: boolean;
    rate_limit?: number;
    id: string;
    key: string;
    total_calls: number;
    last_used_at?: (string | null);
    created_at?: (string | null);
    user_id: string;
};

export type ApiKeysPublic = {
    data: Array<ApiKeyPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type SecurityTestReportPublic = {
    task_id: string;
    asset_id: string;
    vulnerability_found?: boolean;
    details?: ({
    [key: string]: unknown;
} | null);
    id: string;
    created_at: (string | null);
};

export type SecurityTestReportsPublic = {
    data: Array<SecurityTestReportPublic>;
    count: number;
};

export type SecurityTestTask = {
    target_asset_id: string;
    status?: string;
    payload_type: string;
    id?: string;
    created_at?: (string | null);
    finished_at?: (string | null);
};

export type SourceType = 'auto_discovered' | 'documented' | 'mocked' | 'zombie';

export type Statistics = {
    /**
     * 收藏数
     */
    collect_count?: (number | null);
    /**
     * 评论数
     */
    comment_count?: (number | null);
    /**
     * 点赞数
     */
    digg_count?: (number | null);
    /**
     * 下载数（可能为 null 或缺失）
     */
    download_count?: (number | null);
    /**
     * 分享数
     */
    share_count?: (number | null);
};

export type SystemModulesStatsResponse = {
    data: Array<SystemModuleStats>;
    count: number;
};

export type SystemModuleStats = {
    id: string;
    name: string;
    service_name: string;
    description: (string | null);
    interfaces: number;
    documented: number;
    shadow: number;
    last_scanned_at: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrafficRecordPublic = {
    endpoint_id?: (string | null);
    method: string;
    real_uri: string;
    headers?: ({
    [key: string]: unknown;
} | null);
    body?: (string | null);
    source_ip?: (string | null);
    id: string;
    created_at: (string | null);
};

export type TrafficRecordsPublic = {
    data: Array<TrafficRecordPublic>;
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VideoData = {
    /**
     * 音频（BGM）直链
     */
    audio_url?: (string | null);
    /**
     * 作品 ID
     */
    aweme_id?: (string | null);
    /**
     * 封面图直链
     */
    cover_url?: (string | null);
    /**
     * 发布时间（格式化后的字符串）
     */
    create_time?: (string | null);
    /**
     * 作品文案/描述
     */
    desc?: (string | null);
    /**
     * 时长（单位以第三方返回为准）
     */
    duration?: (number | null);
    /**
     * 统计信息
     */
    statistics?: (Statistics | null);
    /**
     * 标题（通常与 desc 一致）
     */
    title?: (string | null);
    /**
     * 视频播放直链
     */
    video_url?: (string | null);
};

export type VideoResponse = {
    /**
     * 提示信息
     */
    message?: (string | null);
    /**
     * 解析出的作品数据
     */
    data?: (VideoData | null);
};

export type ApiKeysReadApiKeysData = {
    limit?: number;
    skip?: number;
};

export type ApiKeysReadApiKeysResponse = (ApiKeysPublic);

export type ApiKeysCreateApiKeyData = {
    requestBody: ApiKeyCreate;
};

export type ApiKeysCreateApiKeyResponse = (ApiKeyPublic);

export type ApiKeysDeleteApiKeyData = {
    id: string;
};

export type ApiKeysDeleteApiKeyResponse = (Message);

export type CollectCollectTrafficResponse = (unknown);

export type CollectCollectTraffic1Response = (unknown);

export type CollectCollectTraffic2Response = (unknown);

export type CollectCollectTraffic3Response = (unknown);

export type CollectCollectTraffic4Response = (unknown);

export type CollectCollectTraffic5Response = (void);

export type CollectCollectTraffic6Response = (unknown);

export type DouyinFetchOneVideoByShareUrlData = {
    /**
     * Douyin share URL
     */
    shareUrl: string;
};

export type DouyinFetchOneVideoByShareUrlResponse = (VideoResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: UserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SecurityAssetsReadAssetsData = {
    limit?: number;
    skip?: number;
};

export type SecurityAssetsReadAssetsResponse = (ApiAssetsPublic);

export type SecurityAssetsTriggerScanData = {
    assetId: string;
    payloadType?: string;
};

export type SecurityAssetsTriggerScanResponse = (SecurityTestTask);

export type SecurityAssetsReadReportsData = {
    limit?: number;
    skip?: number;
};

export type SecurityAssetsReadReportsResponse = (SecurityTestReportsPublic);

export type SystemModulesGetSystemModulesStatsResponse = (SystemModulesStatsResponse);

export type SystemModulesGetModuleEndpointsData = {
    limit?: number;
    moduleId: string;
    skip?: number;
};

export type SystemModulesGetModuleEndpointsResponse = (ApiEndpointsPublic);

export type SystemModulesGetModuleEndpointDetailData = {
    endpointId: string;
    moduleId: string;
};

export type SystemModulesGetModuleEndpointDetailResponse = (ApiEndpointDetailResponse);

export type TrafficManagerGetConfigResponse = ({
    [key: string]: unknown;
});

export type TrafficManagerToggleConfigData = {
    enabled: boolean;
};

export type TrafficManagerToggleConfigResponse = ({
    [key: string]: unknown;
});

export type TrafficManagerImportApifoxData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type TrafficManagerImportApifoxResponse = ({
    [key: string]: unknown;
});

export type TrafficManagerGetEndpointTrafficData = {
    endpointId: string;
    limit?: number;
    skip?: number;
};

export type TrafficManagerGetEndpointTrafficResponse = (TrafficRecordsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);