/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutServicesRouteImport } from './routes/_layout/services'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutServicesIndexRouteImport } from './routes/_layout/services/index'
import { Route as LayoutBusinessConfigIndexRouteImport } from './routes/_layout/business-config/index'
import { Route as LayoutServicesServiceIdIndexRouteImport } from './routes/_layout/services/$serviceId/index'
import { Route as LayoutServicesServiceIdEndpointIdRouteImport } from './routes/_layout/services/$serviceId/$endpointId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesRoute = LayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesIndexRoute = LayoutServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutServicesRoute,
} as any)
const LayoutBusinessConfigIndexRoute =
  LayoutBusinessConfigIndexRouteImport.update({
    id: '/business-config/',
    path: '/business-config/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutServicesServiceIdIndexRoute =
  LayoutServicesServiceIdIndexRouteImport.update({
    id: '/$serviceId/',
    path: '/$serviceId/',
    getParentRoute: () => LayoutServicesRoute,
  } as any)
const LayoutServicesServiceIdEndpointIdRoute =
  LayoutServicesServiceIdEndpointIdRouteImport.update({
    id: '/$serviceId/$endpointId',
    path: '/$serviceId/$endpointId',
    getParentRoute: () => LayoutServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/services': typeof LayoutServicesRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/business-config/': typeof LayoutBusinessConfigIndexRoute
  '/services/': typeof LayoutServicesIndexRoute
  '/services/$serviceId/$endpointId': typeof LayoutServicesServiceIdEndpointIdRoute
  '/services/$serviceId/': typeof LayoutServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/business-config': typeof LayoutBusinessConfigIndexRoute
  '/services': typeof LayoutServicesIndexRoute
  '/services/$serviceId/$endpointId': typeof LayoutServicesServiceIdEndpointIdRoute
  '/services/$serviceId': typeof LayoutServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/services': typeof LayoutServicesRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/business-config/': typeof LayoutBusinessConfigIndexRoute
  '/_layout/services/': typeof LayoutServicesIndexRoute
  '/_layout/services/$serviceId/$endpointId': typeof LayoutServicesServiceIdEndpointIdRoute
  '/_layout/services/$serviceId/': typeof LayoutServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/services'
    | '/settings'
    | '/business-config/'
    | '/services/'
    | '/services/$serviceId/$endpointId'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/business-config'
    | '/services'
    | '/services/$serviceId/$endpointId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/services'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/business-config/'
    | '/_layout/services/'
    | '/_layout/services/$serviceId/$endpointId'
    | '/_layout/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services': {
      id: '/_layout/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LayoutServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services/': {
      id: '/_layout/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof LayoutServicesIndexRouteImport
      parentRoute: typeof LayoutServicesRoute
    }
    '/_layout/business-config/': {
      id: '/_layout/business-config/'
      path: '/business-config'
      fullPath: '/business-config/'
      preLoaderRoute: typeof LayoutBusinessConfigIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services/$serviceId/': {
      id: '/_layout/services/$serviceId/'
      path: '/$serviceId'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof LayoutServicesServiceIdIndexRouteImport
      parentRoute: typeof LayoutServicesRoute
    }
    '/_layout/services/$serviceId/$endpointId': {
      id: '/_layout/services/$serviceId/$endpointId'
      path: '/$serviceId/$endpointId'
      fullPath: '/services/$serviceId/$endpointId'
      preLoaderRoute: typeof LayoutServicesServiceIdEndpointIdRouteImport
      parentRoute: typeof LayoutServicesRoute
    }
  }
}

interface LayoutServicesRouteChildren {
  LayoutServicesIndexRoute: typeof LayoutServicesIndexRoute
  LayoutServicesServiceIdEndpointIdRoute: typeof LayoutServicesServiceIdEndpointIdRoute
  LayoutServicesServiceIdIndexRoute: typeof LayoutServicesServiceIdIndexRoute
}

const LayoutServicesRouteChildren: LayoutServicesRouteChildren = {
  LayoutServicesIndexRoute: LayoutServicesIndexRoute,
  LayoutServicesServiceIdEndpointIdRoute:
    LayoutServicesServiceIdEndpointIdRoute,
  LayoutServicesServiceIdIndexRoute: LayoutServicesServiceIdIndexRoute,
}

const LayoutServicesRouteWithChildren = LayoutServicesRoute._addFileChildren(
  LayoutServicesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutServicesRoute: typeof LayoutServicesRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBusinessConfigIndexRoute: typeof LayoutBusinessConfigIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutServicesRoute: LayoutServicesRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBusinessConfigIndexRoute: LayoutBusinessConfigIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
